### ISSUE TITLE
HierarchicalLifetimeStrategy migration

### ISSUE THREAD

**Issue by bohbra** [unitycontainer/container#157] opened 2019-04-14 18:11 UTC
### Description

I'm updating Unity from 3.5.1404 to 5.10.3 and I'm not able to compile the project because of a custom extension.  I'm not sure if something like this is just not supported anymore or if there's an alternative. 

### To Reproduce

```C#
public class HierarchicalLifetimeExtension : UnityContainerExtension
{
    protected override void Initialize()
    {
        Context.Strategies.Add(new HierarchicalLifetimeStrategy(), UnityBuildStage.TypeMapping);
    }
}

public class HierarchicalLifetimeStrategy : BuilderStrategy
{
    public override void PreBuildUp(ref BuilderContext context)
    {
        var activeLifetime = context.Get<ILifetimePolicy>(context.BuildKey);
        if (activeLifetime is HierarchicalLifetimeManager)
        {          
            var localLifetime = context.PersistentPolicies.Get<ILifetimePolicy>(context.BuildKey, true);
            if (localLifetime == null)
            {
                context.PersistentPolicies.Set<ILifetimePolicy>(new HierarchicalLifetimeManager(), context.BuildKey);
            }
        }

        base.PreBuildUp(ref context);
    }
}

public class HierarchicalLifetimeManager : ExternallyControlledLifetimeManager
{

}
```

**Comment by ENikS** [comment] 2019-04-16 02:03
Perhaps [this](https://github.com/unitycontainer/unity/wiki/Upgrading-Unity-Container-to-the-latest-(Changelog)) might help

**Comment by bohbra** [comment] 2019-04-16 03:43
I couldn't find a fix for this specific problem in the wiki.  

I see that a lot of people are using [a similar class](https://github.com/search?q=HierarchicalLifetimeStrategy&type=Code) but nobody is using a current version of unity.  I imagine they will run into the same issues as me.

Here is a screenshot of the build issue to be a little more clear:

![image](https://user-images.githubusercontent.com/490162/56180592-d6949f00-5fbe-11e9-92e6-cf0d15ca6c82.png)

Is there a different property or class to use to get the `PersistentPolicies`? Or is that deprecated?

**Comment by ENikS** [comment] 2019-04-16 03:53
To get persistence policy you need to call Get<LifetimeManager>

**Comment by bohbra** [comment] 2019-04-16 05:51
I took another stab at this but I'm really struggling with it.  I couldn't quite find a Get<LifetimeManager> but in the unity source I found usages of `context.Get(typeof(LifetimeManager))` which I assume is equivalent, is that correct?  Is there an API to determine if it's a local lifetime or not? 

```C#
public override void PreBuildUp(ref BuilderContext context)
{
    var activeLifetime = (LifetimeManager) context.Get(typeof(LifetimeManager));
    if (activeLifetime is HierarchicalLifetimeManager)
    {
        var localLifetime = (LifetimeManager) context.Get(typeof(LifetimeManager), true); // how do you get the local lifetime?
        if (localLifetime == null)
        {
            activeLifetime.SetValue(new HierarchicalLifetimeManager()); // this doesn't make sense
        }
    }
}
```

**Comment by Ledragon** [comment] 2019-04-16 08:24
Facing the same kind of issue while trying to update from 5.8 and doing
`this.Context.Policies.Set<ILifetimePolicy>(lifetimeManager, new NamedTypeBuildKey(e.TypeTo, e.Name));`

The `ILifeTimePolicy` does not seem to exist anymore, or was it moved maybe?

**Comment by ENikS** [comment] 2019-04-16 12:04
This is how lifetime is handled in Unity:

https://github.com/unitycontainer/container/blob/master/src/Strategies/LifetimeStrategy.cs

Perhaps if you explain what you are trying to accomplish, I could help you better.

**Comment by ENikS** [comment] 2019-04-16 12:06
This is how lifetime is handled by the container:

https://github.com/unitycontainer/container/blob/master/src/Strategies/LifetimeStrategy.cs

**Comment by bohbra** [comment] 2019-04-17 16:37
I'm trying to create a new Lifetime manager that is both [ExternallyControlled](https://github.com/unitycontainer/abstractions/blob/master/src/Lifetime/Managers/ExternallyControlledLifetimeManager.cs) and [Hierarchical](https://github.com/unitycontainer/abstractions/blob/master/src/Lifetime/Managers/HierarchicalLifetimeManager.cs)

**Comment by ENikS** [comment] 2019-04-18 13:42
To get the lifetime manager:

```c#
LifetimeManager policy = null;
    if (context.Registration is ContainerRegistration registration)
        policy = registration.LifetimeManager;
    else
        policy = context.Registration.Get(typeof(LifetimeManager));
```

**Comment by ENikS** [comment] 2019-04-24 00:00
I do not think this is an issue, rather a question, so I am closing it.

**Comment by marquesmps** [comment] 2020-08-24 15:03
@bohbra  How did you end up migrating this code?

**Comment by bohbra** [comment] 2020-08-24 16:55
@marquesmps I abandoned the migration, couldn't find a solution to this.

**Comment by ENikS** [comment] 2020-08-24 16:56
Do you want me to help, I though you handled it

**Comment by ENikS** [comment] 2020-08-24 16:59
If you create a test case demonstrating your issue with latest Unity I could try solving it

**Comment by k1laba** [comment] 2021-07-29 09:31
Because of circular dependecy in our codebase, we are adding a strategy for `PerResolveLifetimeManager` with `UnityBuildStage.TypeMapping` build stage (before any built in Lifetime steps). Default Transient lifetime does not work with circular dependency. 
We are trying to upgrade from 4.x to 5.x but we are unable to do same thing for version 5.x. This is a code snippet we are using to register `PerResolveLifetimeManager` with version 4.x:

```
public void PreBuildUp(IBuilderContext context)
{
    ILifetimePolicy existing = context.Policies.Get<ILifetimePolicy>(context.BuildKey);

    if (existing == null)
    {
        context.PersistentPolicies.Set<ILifetimePolicy>(new PerResolveLifetimeManager(), context.BuildKey);
    }
}
```

Is there anything similar we can do with version 5.x instead of doing huge refactoring to drop circular dependencies? Could not find anything useful in docs.

**Comment by ENikS** [comment] 2021-07-29 14:46
Did you try Diagnostic extension?

**Comment by k1laba** [comment] 2021-07-30 10:56
> Did you try Diagnostic extension?

Thanks for your quick reply. From my understanding diagnostic extension is used to get more information about exception, correct? But we already know the root cause and it is circular dependency. I know, it's not the best design, but it would be a huge refactoring to drop circular dependency in existing codebase. I am looking for a similar way we were using for 4.x to Register `PerResolveLifetimeManager` globally and not for individual type mappings. Anyway, I have added a Diagnostic extensions and instead of generic `StackOverflowException` I have received a circular dependency error:

```
Unity.ResolutionFailedException: 'Circular reference: Type: ....
CircularDependencyException: Circular reference: Type: 
```

**Comment by ENikS** [comment] 2021-07-30 18:09
Would you like to hire me as a consultant? I can help you with your upgrade.

**Comment by k1laba** [comment] 2021-08-04 13:51
We have decided to hold off its upgrade for now, because it was not straightforward.

**Closed** 2021-08-09 16:11 UTC
Labels: Question :grey_question:, release
